### ISSUE TITLE
Cannot install: "Could not find a version that satisfies the requirement urllib"

### ISSUE THREAD

**Issue by kuba-orlik** [nateshmbhat/Yify-Python#2]
When trying to install pyYify via `pip`, I get:

```
Collecting pyYify
  Using cached https://files.pythonhosted.org/packages/33/0e/e315e9d156abf4ed522c74ca003c753ac7337be1422e9bf750b728bf5135/pyYify-1.9.1-py3-none-any.whl
Collecting bs4 (from pyYify)
  Using cached https://files.pythonhosted.org/packages/10/ed/7e8b97591f6f456174139ec089c769f89a94a1a4025fe967691de971f314/bs4-0.0.1.tar.gz
Requirement already satisfied: requests in /usr/lib/python3.7/site-packages (from pyYify) (2.20.1)
Collecting urllib (from pyYify)
  Could not find a version that satisfies the requirement urllib (from pyYify) (from versions: )
No matching distribution found for urllib (from pyYify)
```

**Comment by TheScottishFly** [comment]
Git clone
Remove urllib, re and json from requirements.txt (already included in Python3)
Remove urllib from setup.py in install_requires
python3.X setup.py install

:)

**Comment by spigelli** [comment]
This method makes the package unusable for me:
`>>> import urllib
>>> import urllib3
>>> import bs4
>>> import requests
>>> import re
>>> from pyYify import yify

>>> movies_list = yify.search_movies("superman")

>>> movies_list
[<class 'pyYify.yify.movie'>, <class 'pyYify.yify.movie'>, <class 'pyYify.yify.movie'>, <class 'pyYify.yify.movie'>, <class 'pyYify.yify.movie'>, <class 'pyYify.yify.movie'>, <class 'pyYify.yify.movie'>]

>>> movies_list[0].name
AttributeError: type object 'movie' has no attribute 'name'

>>> movies_list[0].getinfo()
TypeError: getinfo() missing 1 required positional argument: 'self'

>>> movies_list[0].getinfo(name)
NameError: name 'name' is not defined

>>> movies_list[0].getinfo(id)
  File "C:\Users\\Downloads\pyYify-master\pyYify-master\pyYify\yify.py", line 102, in getinfo
    self.name = re.search("^[^\(]+" ,self.name).group(0).strip() ;
AttributeError: 'builtin_function_or_method' object has no attribute 'name'
`

**Comment by nateshmbhat** [comment]
Removed the libraries from requirements.txt
